# save_as_cookies.py
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time
import os

CONFIG_DIR = os.path.expanduser("~/.config/4kTubeFree")
os.makedirs(CONFIG_DIR, exist_ok=True)
OUT_COOKIES = os.path.join(CONFIG_DIR, "cookies.txt")

def cookies_to_netscape(cookies):
    # Netscape format header
    lines = ["# Netscape HTTP Cookie File", "# This file is generated by 4KTubeFree", ""]
    for c in cookies:
        # domain, include_subdomains (TRUE/FALSE), path, secure (TRUE/FALSE), expiry, name, value
        domain = c.get("domain", "")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = str(c.get("expiry", 0))
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([domain, include_subdomains, path, secure, expiry, name, value]))
    return "\n".join(lines)

def run_login_and_export_cookies():
    # Chrome options: show normal window (don't headless), so user can interact (and 2FA/captcha yapabilir)
    options = webdriver.ChromeOptions()
    options.add_argument("--start-maximized")

    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
    try:
        # Aç: Google login sayfası (veya direkt youtube)
        driver.get("https://accounts.google.com/ServiceLogin?hl=tr&passive=true&continue=https://www.youtube.com/")
        print("Tarayıcı açıldı. Lütfen Google hesabınızla giriş yapın.")

        # Burada kullanıcı girişini manuel tamamlayacak. Biz oturum açıldığını algılayana kadar bekleriz.
        # Basit bir bekleme: ana YouTube sayfası yüklendiğine dair kontrol (örnek)
        max_wait = 300  # saniye, örn. 5 dakika bekle
        waited = 0
        while waited < max_wait:
            time.sleep(1)
            waited += 1
            if "youtube.com" in driver.current_url and "accounts.google" not in driver.current_url:
                # Muhtemelen giriş tamamlandı ve YouTube'ya yönlendirildi
                break

        # Alternatif: belirli cookie var mı diye bakabilirsin, örn 'SAPISID' veya 'SID' gibi Google cookie'leri
        cookies = driver.get_cookies()
        if not cookies:
            print("Çerez alınamadı — giriş yapılmamış olabilir.")
        else:
            text = cookies_to_netscape(cookies)
            with open(OUT_COOKIES, "w", encoding="utf-8") as f:
                f.write(text)
            print(f"Cookies kaydedildi: {OUT_COOKIES}")

    finally:
        driver.quit()

if __name__ == "__main__":
    run_login_and_export_cookies()
